---

- name: Create the dungeon
  hosts: all 
  become: yes

  tasks:
  - name: Copy over the mongo repo config
    copy:
      src: mongo_config
      dest: /etc/yum.repos.d/mongodb-org-3.4.repo

  - name: Install mongoDB
    yum:
      name: mongodb-org
      state: latest
    become: yes

  - name: Restart MongoDB
    service: name=mongod state=restarted
    become: yes

  - name: Download mongo exporter
    get_url:
      url: https://github.com/percona/mongodb_exporter/releases/download/v0.7.1/mongodb_exporter-0.7.1.linux-amd64.tar.gz
      dest: /etc/mongodb_exporter-0.7.1.linux-amd64.tar.gz

#  - name: unarchive the mongo exporter
#    unarchive:
#      src: /etc/mongodb_exporter-0.7.1.linux-amd64.tar.gz

  - name: Download the node exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
